### ISSUE TITLE
Countdown startet neu, wenn man App komplett schließt

### ISSUE THREAD

**Issue by fenzj** [Wunderbyte-GmbH/moodle-mod_mooduell#30]
Momentan wenn man eine Frage liest, danach die App beendet und dann die App wieder neu startet kommt man wieder zu der selben Frage und der Countdown beginnt wieder von neu.

Durch das kann man den Sinn des Countdowns recht leicht umgehen und alle Fragen ganz leicht ohne Zeitlimit nachschauen.

**Comment by georgmaisser** [comment]
fixed in Version vom 23.11.2020. Die neue Funktionalität: Die Frage wird bei der Rückkehr mit dem aktuellen Status eingecheckt (wären bereits die richtigen Antworten eingecheckt, wäre die Frage also richtig beantwortet), man kommt gleich zur nächsten Frage. Man könnte die Funktion natürlich auch so machen, dass NICHT die nächste Frage gleich kommt, sondern dass der Überblicksscreen angezeigt wird. Können wir gerne noch nach Euren Präferenzen anpassen.
